#!/bin/bash
#
pyinstaller --windowed \
            --noconfirm \
            --icon="$GITHUB/coffeegrindsize/build_tools/coffeegrindsize.icns" \
            --name "coffeegrindsize" \
            --hidden-import cmath \
            $GITHUB/coffeegrindsize/coffeegrindsize.py
