#!/bin/bash
#
pyinstaller --windowed \
            --noconfirm \
            --icon="$GITHUB/coffeegrindsize/build_tools/coffeegrindsize.icns" \
            --name "coffeegrindsize" \
            --hidden-import cmath \
            $GITHUB/coffeegrindsize/coffeegrindsize.py
$GITHUB/coffeegrindsize/build_tools/fix_info_plist.py ./dist/coffeegrindsize.app/Contents/Info.plist
